# Generated by Django 2.2 on 2020-07-11 14:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('1', 'corporate head office'), ('2', 'branch office')], max_length=30)),
                ('incident_description', models.CharField(max_length=100)),
                ('date_and_time_of_incident', models.DateTimeField(max_length=100)),
                ('incident_location', models.CharField(max_length=100)),
                ('initial_severity', models.CharField(choices=[('1', 'severe'), ('2', 'moderate'), ('3', 'easy')], max_length=30)),
                ('suspected_cause', models.CharField(max_length=100)),
                ('immediate_actions_taken', models.CharField(max_length=100)),
                ('sub_incident_types', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'environmental incident'), ('2', 'injury/illness'), ('3', 'property damage'), ('4', 'vehicle')], max_length=7)),
                ('reported_by', models.CharField(max_length=100)),
            ],
        ),
    ]
