# Generated by Django 2.2 on 2020-07-12 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_and_time_of_incident',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 12, 6, 45, 34, 473589)),
        ),
    ]
